[toolchain]
anchor_version = "1.0.0"

[features]
resolution = true
skip-lint = false

[programs.devnet]
solsutara = "3Kzq31P89HkR8SEofcmE8AU52pCdAxyFUwwFFscJHxgm"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[workspace]
members = ["program"]

[scripts]
test = "ts-node client/tests/testComponents.ts"

[hooks]
