[package]
name = "solsutara"
version = "0.1.0"
description = "SolSutara — decentralized supply chain traceability on Solana"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "solsutara"

[features]
no-entrypoint = []
no-idl = []
no-log-ix-name = []
cpi = ["no-entrypoint"]
idl-build = ["anchor-lang/idl-build"]
default = []

[dependencies]
anchor-lang = "1.0.0"
